name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    # - name: npm install
    #   run: npm install
    
    - name: Installing cdk cli
      run: npm i aws-cdk
    
    - name: cdk version
      run: cdk --version

    # - name: Building cdk stack...
    #   run: ./node_modules/.bin/cdk build
    
    # - name: Building rust code...
    #   run: cargo build --verbose --release --manifest-path ./lambda-rust/Cargo.toml
    
    # - name: Renaming to bootstrap...
    #   run: cp ./lambda-rust/target/release/lambda-rust ./bootstrap
    
    # - name: Creating lambda.zip
    #   run: zip lambda.zip bootstrap
    
    # - name: Installing cdk cli...
    #   run: npm i -g aws-cdk
    


    # - name: Building cdk stack...
    #   run: ./node_modules/.bin/cdk build
    
    # - name: Deplloing cdk stack...
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    #   run: cdk deploy
