name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install cdk
      run: sudo npm install -g aws-cdk
    
    - name: cdk version
      run: cdk --version

    - name: npm install
      run: npm install

    - name: npm run build
      run: npm run build

    - name: docker build
      run: docker run --rm -v ${PWD}/lambda-rust:/code softprops/lambda-rust

    - name: cp zip
      run: cp ./lambda-rust/target/lambda/release/lambda-rust.zip ./lambda-rust.zip

    - name: cdk deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: cdk deploy --require-approval never